### ISSUE TITLE
xtl payments

### ISSUE THREAD

**Issue by alexmateescu** [1rV1N-git/nodejs-pool#42]
hi. i am trying to use your payment file for XTL and the error i am getting is: 
|payments | 2018-06-21 02:27:23:396 +03:00: Adding payment for 2 miners
4|payments | 2018-06-21 02:27:23:732 +03:00: Current wallet balance is 16310.74 with 16310.74 unlocked balance
4|payments | 2018-06-21 02:27:23:741 +03:00: Issue making payments: {"code":-32602,"message":"Invalid params"}
4|payments | 2018-06-21 02:27:23:741 +03:00: Will not make more payments until the payment daemon is restarted!

Can you help me to fix it please?

**Comment by 1rV1N-git** [comment]
@alexmateescu  problem solved in discord
close plz

**Comment by alexmateescu** [comment]
wrong denomination set
